using Test
using SVGPlots

x = collect(-4:0.1:4)
figure(;width=800, height=600)
subplot(2,3,1)
plot(x, x)
hold(true)
plot(x, x.^2)
subplot(2,3,2)
plot(x, x.^2)
subplot(2,3,3)
plot(x, x.^3)
subplot(2,3,4)
plot(x, x.^4)
subplot(2,3,5)
plot(x, x.^5)
subplot(2,3,6)
plot(x, x.^6)
display(gcf())
figure()
plot(x, x)
hold(true)
plot(x, x.^2, linetype = :dotted)
plot(x, x.^3, linetype = :dashed)
plot(x, x.^4, linetype = :dashdotted)
plot(x, x.^5, linetype = :none)
title("This is a title")
xlabel("x")
ylabel("y")
display(gcf())
figure()
subplot(2,2,1)
plot(x, x)
subplot(2,2,2)
plot(x, x.^2)
subplot(2,2,3)
plot(x, x.^3)
subplot(2,2,4)
plot(x, x.^4)
hold(true)
plot(x, x.^5)
title("test")
display(gcf())
